version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=workout_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=workout_planner
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=workout_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=workout_planner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workout_user -d workout_planner"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: